power_data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?")
power_data <- subset(power_data, Date == "1/2/2007" | Date == "2/2/2007")
png("plot1.png")
with(power_data2, hist(Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", ylab="Frequency", col="red"))
dev.off()